# Generated by Django 6.1.1 on 2026-09-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.CharField(db_index=True, max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=128)),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "price_per_gallon",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="routing_fue_latitud_6dc999_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("opis_id", "name"), name="unique_station"
                    )
                ],
            },
        ),
    ]
